# Generated by Django 5.1.2 on 2024-10-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='on_list',
            field=models.BooleanField(default=True),
        ),
    ]
